### ISSUE TITLE
Ability to move or hide the button adjacent to micro menu

### ISSUE THREAD

**Issue by Oddezt** [Saaappi/HelpMePlay#85]
Hi!

Would it be possible to add an option to move or hide the button adjacent to the micro menu? I currently have my micro bar as mouseover so it it strange to have the button always displayed.

Thanks!

**Comment by Saaappi** [comment]
Hi @Oddezt,

I don't plan to make it moveable, but I can determine if it's possible to make it respect the visibility condition of the micro menu. What addon do you use to hide it except on hover?

**Comment by Oddezt** [comment]
Thank you! I use ElvUI and choose 'mouseover' from there.

**Comment by Saaappi** [comment]
This has been addressed in 64ab9c8. See below.

![HideMicroMenuBarButton](https://github.com/user-attachments/assets/53408f38-3c79-442a-acc2-d953e9f137f0)

**Comment by Oddezt** [comment]
Hi, sorry to bother you again! I can't seem to get this to work on my end. The micro menu button is still always visible. Thanks!

**Comment by Saaappi** [comment]
This won't be available until the release of 3.0.5. The hotfix build that went out today is not a content update, and therefore has none of my work scheduled for August 27.

**Comment by Oddezt** [comment]
@Saaappi Hey again! Sorry to have to post about this again - but I've just downloaded the latest update of HelpMePlay (3.1.0) and I am still unable to get the button to adhere to the ElvUI mouseover conditions. Is there a setting that I need to enable? Thanks!

**Comment by Saaappi** [comment]
@Oddezt 

I've reopened the issue and will investigate.

Would you be able to send me a copy of the ElvUI saved variables for your main character? (The one you checked if the mouseover setting is working.)

My initial guess is HelpMePlay can't determine whether it's enabled or not, and therefore it keeps the icon shown.

**Comment by Oddezt** [comment]
@Saaappi 

Of course! What is the best way for me to send it across to you?

**Comment by Saaappi** [comment]
You should be able to attach a file directly to a comment.

I need the _ElvUI.lua_ file from `C:\Program Files (x86)\World of Warcraft\_retail_\WTF\Account\{GUID}\SavedVariables`, where `{GUID}` will be your account's unique identifier.

**Comment by Oddezt** [comment]
You can't attach LUA files to comments unfortunately.

**Comment by Saaappi** [comment]
Compress the file to `.zip` format and upload that instead.

**Comment by Oddezt** [comment]
[ElvUI.zip](https://github.com/user-attachments/files/16752363/ElvUI.zip)

Done!

**Comment by Saaappi** [comment]
e491fd8 should have this resolved. Extract the file below and replace the _MainMenuBar.lua_ file at the root of the addon folder. If you're not asked "Are you sure you want to replace this file", or something similar, then you pasted it in the wrong folder.

Let me know if you have any additional issues.

[MainMenuBar.zip](https://github.com/user-attachments/files/16752636/MainMenuBar.zip)

**Comment by Oddezt** [comment]
Thank you! That has fixed it!
